apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJSR1Z1ZVVGc1lYSmpiMjQ2WjJod1gyZG9aazVtVG1sak1rVmFTbE5DYldWa00zSnRZVGhZVmpObldUaFZjVEExTUVSUmJRPT0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogIndpbmNyZWQiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9Cgl9LAoJImZlYXR1cmVzIjogewoJCSJob29rcyI6ICJ0cnVlIgoJfQp9
type: kubernetes.io/dockerconfigjson
